apiVersion: v1
kind: Service
metadata:
  name: home-bills-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: home-bills-rails-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http