apiVersion: v1
kind: Service
metadata:
  name: home-bills-rails-app-svc
spec:
  sessionAffinity: None
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  type: NodePort
  selector:
    app: home-bills-rails-app
