test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

google:
 service: GCS
 project: <%= ENV['CLOUD_STORAGE_PROJECT_NAME'] %>
 credentials: <%= ENV['CLOUD_STORAGE_CREDENTIALS'] %>
 bucket: <%= ENV['CLOUD_STORAGE_BUCKET_NAME'] %>

google_dev:
  service: GCS
  project:  <%= ENV['CLOUD_STORAGE_PROJECT_NAME'] %>
  credentials: <%= Rails.root.join("config/secrets/cloud-storage-credentials.json") %>
  bucket: <%= ENV['CLOUD_STORAGE_BUCKET_NAME'] %>
